apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: tidb
  labels:
    {{- include "tidb.labels" . | nindent 4 }}
spec:
  connectionCredential:
    username: root
    password: ""
    endpoint: "$(SVC_FQDN):$(SVC_PORT_pd-client)"
    host: "$(SVC_FQDN)"
    port: "$(SVC_PORT_pd-client)"
  componentDefs:
    - name: pd
      characterType: tidb
      workloadType: Consensus
      rsmSpec:
        roles:
          - name: leader
            accessMode: ReadWrite
            isLeader: true
            canVote: true
          - name: follower
            accessMode: ReadWrite
            isLeader: false
            canVote: true
        # roleProbe:
        #   customHandler:
        #     - image: quay.io/coreos/etcd:v3.5.6
        #       command:
        #         - |
        #           Status=$(etcdctl --endpoints=
      service:
        ports:
          - name: pd-client
            port: 2379
            targetPort: pd-client
          - name: pd-peer
            port: 2380
            targetPort: pd-peer
      podSpec:
        containers:
          - name: pd
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 2379
                name: pd-client
              - containerPort: 2380
                name: pd-peer
            volumeMounts:
              - name: data
                mountPath: /var/lib/pd
            command:
              - bin/sh
              - -c
              - |
                echo "start pd..."
                PEERS=""
                # TODO: clusterDomain 'cluster.local' requires configurable
                DOMAIN=$KB_NAMESPACE".svc{{ .Values.clusterDomain }}"
                i=0
                while [ $i -lt $KB_REPLICA_COUNT ]; do
                	if [ $i -ne 0 ]; then
                		PEERS="$PEERS,";
                	fi;
                	host=$(eval echo \$KB_"$i"_HOSTNAME)
                    host=$host"."$DOMAIN
                    hostname=${KB_CLUSTER_COMP_NAME}-${i}
                	PEERS="$PEERS$hostname=http://$host:2380"
                    i=$(( i + 1))
                done
                # TODO: clusterDomain 'cluster.local' requires configurable
                MY_PEER=$KB_POD_FQDN{{ .Values.clusterDomain }}
                exec /pd-server --name=${HOSTNAME} \
                --data-dir=/var/lib/pd \
                --peer-urls=http://0.0.0.0:2380 \
                --advertise-peer-urls=http://${MY_PEER}:2380 \
                --client-urls=http://0.0.0.0:2379 \
                --advertise-client-urls=http://${MY_PEER}:2379 \
                --initial-cluster=${PEERS}
