apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: tidb
  labels:
    {{- include "tidb.labels" . | nindent 4 }}
spec:
  connectionCredential:
    username: root
    password: ""
    endpoint: "$(SVC_FQDN):$(SVC_PORT_client)"
    host: "$(SVC_FQDN)"
    port: "$(SVC_PORT_client)"
  componentDefs:
    - name: pd
      characterType: tidb
      workloadType: Stateful # NOTE: try to use Consensus with rsmSpec.roleProbe
      statefulSpec:
        updateStrategy: BestEffortParallel
      service:
        ports:
          - name: client
            port: 2379
            targetPort: client
          - name: peer
            port: 2380
            targetPort: peer
      podSpec:
        containers:
          - name: pd
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 2379
                name: client
              - containerPort: 2380
                name: peer
            volumeMounts:
              - name: data
                mountPath: /var/lib/pd
            command:
              - bin/sh
              - -c
              - |
                echo "start pd..."
                # TODO: clusterDomain 'cluster.local' requires configurable
                DOMAIN=$KB_NAMESPACE".svc{{ .Values.clusterDomain }}"
                MY_PEER=$KB_POD_FQDN{{ .Values.clusterDomain }}
                PEERS=""
                i=0
                while [ $i -lt $KB_REPLICA_COUNT ]; do
                	if [ $i -ne 0 ]; then
                		PEERS="$PEERS,";
                	fi;
                	host=$(eval echo \$KB_"$i"_HOSTNAME)
                    host=$host"."$DOMAIN
                    hostname=${KB_CLUSTER_COMP_NAME}-${i}
                	PEERS="$PEERS$hostname=http://$host:2380"
                    i=$(( i + 1))
                done
                exec /pd-server --name=${HOSTNAME} \
                --data-dir=/var/lib/pd \
                --peer-urls=http://0.0.0.0:2380 \
                --advertise-peer-urls=http://${MY_PEER}:2380 \
                --client-urls=http://0.0.0.0:2379 \
                --advertise-client-urls=http://${MY_PEER}:2379 \
                --initial-cluster=${PEERS}
    - name: tikv
      characterType: tidb
      workloadType: Stateful
      statefulSpec:
        updateStrategy: BestEffortParallel
      service:
        ports:
          - name: peer
            port: 20160
            targetPort: peer
      podSpec:
        containers:
          - name: tikv
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 20160
                name: peer
            volumeMounts:
              - name: data
                mountPath: /var/lib/tikv
            command:
              - bin/sh
              - -c
              - |
                echo "start tikv..."
                DOMAIN=$KB_NAMESPACE".svc{{ .Values.clusterDomain }}"
                exec /tikv-server --pd=http://${KB_CLUSTER_NAME}-pd.${DOMAIN}:2379 \
                --data-dir=/var/lib/tikv \
                --addr=0.0.0.0:20160 \
                --advertise-addr=${KB_POD_FQDN}:20160 \
                --status-addr=0.0.0.0:20180
